import type { ContractDataType, PODataType, IMDataType, InvoiceDataType } from "./types"

export const contractData: ContractDataType = {
  Action: "MAD",
  "Contract Number": "CNB10041025",
  "GPO ID": "GPO",
  Status: "A",
  "Contract Start Date": "20250410",
  "Contract End Date": "20260410",
  "GPO Name": "VIZIENTQC",
  "Supplier Type": "M",
  "Org Item ID": "102156",
  "Original Item Desc": "SET FLUID WARMING HOTLINE #L70",
  "MFR ID": "S34|1",
  "MFR Name": "SMITHS MEDICAL SIMMS/PORTEX",
  "MFR Item ID": "L-70",
  "Contract Item Start Date": "20250312",
  "Contract Item End Date": "20251215",
  "Vendor ID": "HMPGMS-P",
  "Vendor Name": "HMPG PHARMACY LLC (HMPGMS-P)",
  "Vendor Item ID": "VCN10102000NHUTPM",
  "Corp Number": "995",
  "Contract UOM": "EA",
  "Contract QOE": "1",
  "Contract Price": "90",
}

export const poData: PODataType = {
  "PO Number": "2025010444",
  "PO Date": "20250401",
  "PO Line Number": "1",
  "PO Qty": "9",
  "PO UOM": "EA",
  "PO Price": "99.9",
  "Vendor number": "V03775",
  "Item Vendor Name": "CARDINAL HEALTH TEST",
  "Item Vendor Item ID": "VCN202503242",
  "MFR ID": "1757",
  "Item MFR Name": "JOHNSON AND JOHNSON HOSPITAL SERV.",
  "Item MFR Item ID": "MCN202503242",
  "Org Item ID": "X2345",
  GL: "299-95001731-8303200",
  "Original Item Desc": "New item 2",
  "Received Qty": "9",
}

export const itemMasterData: IMDataType = {
  "Vendor ID": "91",
  "Vendor Name": "ACCUTOME INC",
  "Vendor Item ID": "250424015A",
  "Org Item ID": "ITM250424015",
  "Item Desc": "Item 250424015",
  "MFR ID": "1319",
  "MFR Name": "WILLIS PRINTING",
  "MFR Item ID": "250424015B",
  "UOM": "EA",
  "QOE": "1",
  "Price": "50",
  "Corp Number": "10",
  "Corp Name": "TIFT REGIONAL MED CENTER",
  "Expense Code Number": "70290",
  "Expense Code Name": "CONTRACT PERSONNEL",
  "Location ID": "2087"
}

export const invoiceData: InvoiceDataType = {
  "Invoice ID": "INV_ID_001",
  "Invoice IDB": "INV_NUM_001",
  "Invoice Number": "INV_NUMBER_001",
  "Invoice Date": "202511191000",
  "Invoice Type": "INV",
  "Corporation Account Number": "CORP001",
  "Vendor Code": "ZIMMUS-P",
  "Due Date": "20251119",
  "Voucher Number": "001",
  "Gross Invoice Amount": "100",
  "Net Invoice Amount": "100",
  "Short Pay Amount": "100",
  "Vendor Term Amount": "100",
  "Freight Amount": "100",
  "State Tax and Provincial Refundable Tax Amount": "100",
  "County Tax Amount": "0.01",
  "City Tax Amount": "0.01",
  "Miscellaneous Amount": "100",
  "Batch Number": "100",
  "PO Record ID": "1001",
  "PO Record IDB": "100",
  "PO Number": "PO001",
  "Note": "Note",
  "Code 1099": "Code1099",
  "Amount 1099": "Amount1099",
  "User Name": "admin",
  "Account Group Record ID": "001",
  "Account Group Record IDB": "001",
  "Bank Account": "2001",
  "Check Number": "NUM001",
  "Reference Number": "NUM001",
  "Check Date": "20251119",
  "Check Amount": "100",
  "Check Name": "admin",
  "Vendor Remit Code": "VEN001",
  "Vendor Remit Name": "Vendor 01",
  "Vendor Term Code": "CODE01",
  "Single Check Indicator": "|",
  "Fiscal Period": "2001",
  "Discount Date": "20251119",
  "Invoice Discount Amount": "10",
  "Invoice Status Field": "1",
  "Interface Status Change Date": "20251119",
  "Record Created Date": "20251119",
  "Record Create User ID": "U001",
  "Record Create User IDB": "UDB001",
  "Record Updated Date": "20251119",
  "Record Update User ID": "U001",
  "Record Update User IDB": "UDB001",
  "User Defined Text Name": "U001",
  "User Defined Text Value": "U001",
  "User Defined Memo Name": "U001",
  "User Defined Memo Value": "U001",
  "User Defined Date Name": "20251119",
  "User Defined Date Value": "20251119",
  "Miscellaneous Discount Amount": "10",
  "Net Payment Amount": "100",
  "Remit Vendor Net Due Days": "1",
  "Vendor Discount Rate": "0.1",
  "Remit Vendor Discount Due Days": "10",
  "End Month Indicator": "~",

  "Invoice Line ID": "INV001",
  "Invoice Line IDB": "INVDB001",
  "Line Invoice ID": "1",
  "Line Invoice IDB": "1",
  "Invoice Line Number": "1",
  "Line Description": "1",
  "Invoice Line Quantity": "1",
  "Invoice Line UOM": "1",
  "Invoice Line Price": "1",
  "Debit Amount Indicator": "1",
  "Invoice Line Pay Price": "1",
  "Line Corporation Account Number": "1",
  "Freight Code": "1",
  "Freight With Tax": "1",
  "State Compound Tax": "1",
  "County Compound Tax": "1",
  "City Compound Tax": "1",
  "Invoice Line Miscellaneous Amount": "1",
  "Approved Price": "1",
  "Approved Quantity": "1",
  "PO Line Record ID": "1",
  "PO Line Record IDB": "1",
  "PO Line Number": "1",
  "PO Price": "1",
  "Item Number": "1",
  "Sub Account Number": "1",
  "Expense Code Account Number": "1",
  "Cost Center Account Number": "1",
  "Line Code 1099": "1",
  "Line Amount 1099": "1",
  "Line Note": "1",
  "Line Discount Amount": "1",
  "Line Discount Rate": "1",
  "Payment Quantity": "1",
  "Payment UOM": "1",
  "Interface Status": "1",
  "Reviewed Date": "1",
  "Discrepant Note Record ID": "1",
  "Discrepant Note Record IDB": "1",
  "Resolved Note Record ID": "1",
  "Resolved Note Record IDB": "1",
  "Deliver Location Record ID": "1",
  "Deliver Location Record IDB": "1",
  "Line Record Created Date": "1",
  "Line Record Create User ID": "1",
  "Line Record Create User IDB": "1",
  "Line Record Updated Date": "1",
  "Line Record Update User ID": "1",
  "Line Record Update User IDB": "1",
  "Misc Discount Amount": "1",
  "Invoice Extended Cost": "1",
  "Project Code": "1",
  "Project Name": "1",
  "Sub Project Code": "1",
  "Sub Project Name": "1",
  "State Province ACC AMT": "1",
  "County ACC AMT": "1",
  "City ACC AMT": "1",
  "FRT State Province ACC AMT": "1",
  "FRT County ACC AMT": "1",
  "FRT City ACC AMT": "1",
}
